name: ReactNative

on: push

defaults:
  run:
    working-directory: react-native-genius-scan-demo

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v2
    - run: npm install
    - run: cd android && ./gradlew assembleRelease
  ios:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install
    - run: cd ios && pod install
    - run: cd ios && xcodebuild archive -workspace demo.xcworkspace -scheme demo CODE_SIGNING_ALLOWED=NO
